@host = http://localhost:5000
@auth = token: Bearer {{ login.response.body.$.accessToken }}


###
# @name login
POST {{ host }}/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
POST  {{ host }}/api/checkout
Content-Type: application/json
{{auth}}

{
     
}